version: "3"

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ${PWD}:/app
            - ./etc/nginx/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network

    php:
        build:
            context: .
            dockerfile: ./etc/docker/php.docker
        container_name: php
        volumes:
            - ${PWD}:/app
        networks:
            - app-network

    mysql:
        image: mysql:latest
        # Fix for PHP MySql bug: https://bugs.php.net/bug.php?id=76243
        command:
            - "--default-authentication-plugin=mysql_native_password"
        container_name: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: r00t
            MYSQL_DATABASE: laravel
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
        # volumes:
            # - ${PWD}/etc/mysql:/var/lib/mysql
        networks:
            - app-network

    rabbitmq:
        image: rabbitmq:management
        container_name: rabbitmq
        ports:
            - "8080:15672"
        environment:
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: pass
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
